#服务端口
server:
  port: 9002

spring:
  application:
    #应用程序名称
    name: cloud-provider-goods

  cloud:
    consul:
      #注册中心的配置
      host: localhost
      port: 8500
      discovery:
        #主机名称
        hostname: 127.0.0.1
        #对外暴露的服务名称
        service-name: ${spring.application.name}
        #是否注册
        register: true

        cloud-provider-goods:
          ribbon:
            #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
            ConnectTimeout: 250    #请求连接的超时时间
            ReadTimeout: 1000       #请求处理的超时时间
            OkToRetryOnAllOperations: true    #对所有操作请求都进行重试
            MaxAutoRetriesNextServer: 1    #切换实例的重试次数
            MaxAutoRetries: 1              #对当前实例的重试次数
