server:
  port: 3344
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          # GitHub上面的git仓库https地址
          uri: https://github.com/huangzhihao0122/microservice-cloud-config.git